### MISC CONFIGS ###
# enable mouse control
set -g mouse on

# start index at 1
set -g base-index 1

# color
set -g default-terminal "screen-256color"

# clipboard
set -s set-clipboard on
set -as terminal-features ',screen-256color:clipboard'

# easy reload of config file
bind r source-file ~/.tmux.conf

set-option -g status-position bottom

# change prefix from C-b to C-e
unbind-key C-b
set-option -g prefix C-a
bind-key C-a send-prefix

### PANES ###
# split panes using | and -
bind \\ split-window -h
bind - split-window -v
unbind '"'
unbind %

# vim like pane switching
bind -r ^ last-window
bind -r h select-pane -L
bind -r s select-pane -R
bind -r t select-pane -U
bind -r n select-pane -D

# increase pane num display time
set -g display-panes-time 4000

# change status bar color
set -g status-style 'bg=white fg=black'
set -g pane-border-style 'fg=red'
set -g pane-active-border-style 'fg=white'
set-option -g mode-style 'bg=white fg=black'


# increase scroll buffer size
set-option -g history-limit 100000

### STATUS BAR ###
# set 24 hour clock on right side of status bar
set-option -g status-right "%H:%M 20%y-%m-%d"

set -g status-left-length 20
